name: 'Dump ENV Vars'
description: 'Dump the environment variables'
runs:
  using: "composite"
  steps:
    - run: env
      shell: bash
      id: dump-env
    - run: echo "${{ github.ref }}"
      shell: bash
